### PR TITLE
LRQA-33580 Turn on 'test.assert.warning.exceptions' by default on all functional tests

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRQA-33580

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
I stopped the normal pull request, will run a gauntlet test near the end of the day to get results to be analyzed later this week.

Results should show up in this routine:
https://testray-uat.liferay.com/web/guest/home/-/testray/builds?testrayRoutineId=84678476

**Comment by michaelhashimoto** [comment]
ci:retest:gauntlet

**Comment by vicnate5** [comment]
Thanks @michaelhashimoto!

**Comment by michaelhashimoto** [comment]
ci:retest:gauntlet

**Comment by vicnate5** [comment]
@michaelhashimoto For now, we are done with this job

**Comment by vicnate5** [comment]
ci:close

**Pull request closed without merging**
