### PR TITLE
DB_UPGRADE

### PR DESCRIPTION
**Pull request by michaelhashimoto**
Try out the new database dumps

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by vicnate5** [comment]
Sybase failure known issue https://issues.liferay.com/browse/LPS-66085

**Comment by vicnate5** [comment]
MariaDB failure is because the test assumes the user does not need to agree to the terms of use again at login. I will look into this.

**Comment by vicnate5** [comment]
MariaDB failed because the database dump did not get imported.

`[java] 00:06:52,090 WARN  [main][ReleaseLocalServiceImpl:226] Table 'lportal.Release_' doesn't exist`

I tested manually and did not get the same behavior on MariaDB 10.0

**Comment by pyoo47** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@vicnate5 @pyoo47

After these tests ran, I pushed a request to turn on MariaDB & Oracle:
https://github.com/brianchandotcom/liferay-portal/pull/40322

We still need Sybase to work.

I fixed the branch to get past rebase errors.

**Comment by vicnate5** [comment]
@michaelhashimoto The Sybase tests were passing here https://github.com/vicnate5/liferay-portal/pull/379#issuecomment-222795254.

**Comment by michaelhashimoto** [comment]
ci:retest

**Pull request closed without merging**
