### PR TITLE
master-qa-10616

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-10616
https://issues.liferay.com/browse/LRQA-18089

### CODE REVIEW

**Comment by kenjiheigel** [comment]
A few things to note: 
I had to update the java-client jar for appium to the latest version, so we have access to methods like hideKeyboard. hideKeyboard is necessary for the test, because it messes with the coordinates, especially as we use javascript to scroll elements into view. I also made our hideKeyboard check if the keyboard is visible, and to hide it automatically before tapping. 

Also, the last two commits contain things that will need to be backported. But the rest of it is all in poshi runner source. 

Let me know if you have any questions!

**Comment by kenjiheigel** [comment]
Just added some changes from running formatSource

**Comment by kenjiheigel** [comment]
Failed because the constructor for our WebDriver impl's have been updated. I pushed changes to account for this.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
Pushed to BChan. (poshi)
https://github.com/brianchandotcom/liferay-portal/pull/30637

**Pull request closed without merging**
