### PR TITLE
master-qa-16493

### PR DESCRIPTION
**Pull request by lesliewong92**
https://issues.liferay.com/browse/LRQA-16493

### CODE REVIEW

**Comment by lesliewong92** [comment]
ci:retest

**Comment by lesliewong92** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
Pushed to BChan. (move ignorable list out of poshi runner) (part 1)
https://github.com/brianchandotcom/liferay-portal/pull/28450
https://github.com/brianchandotcom/liferay-portal-ee/pull/10810
https://github.com/brianchandotcom/liferay-portal-ee/pull/10811
https://github.com/brianchandotcom/liferay-portal-ee/pull/10812
https://github.com/brianchandotcom/liferay-portal-ee/pull/10813

**Comment by michaelhashimoto** [comment]
Pushed to BChan. (move ignorable list out of poshi runner) (part 2)
https://github.com/brianchandotcom/liferay-portal/pull/28452

**Pull request closed without merging**
