### PR TITLE
master-LRQA-22452

### PR DESCRIPTION
**Pull request by stmerriss**
https://issues.liferay.com/browse/LRQA-22452

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by stmerriss** [comment]
ci:retest

**Comment by stmerriss** [comment]
ci:retest

**Comment by stmerriss** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/36972
https://github.com/brianchandotcom/liferay-portal-ee/pull/12586
https://github.com/brianchandotcom/liferay-portal-ee/pull/12587
https://github.com/brianchandotcom/liferay-portal-ee/pull/12588
https://github.com/brianchandotcom/liferay-portal-ee/pull/12589

**Pull request closed without merging**
