### PR TITLE
LRCI-3588 Add ability to deploy a client extension with a portal instance

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-3588

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by gamerson** [comment]
hey @michaelhashimoto  can you talk with @drew brokke?  He can show you (or I can show you) how you can add a `client-extension.poshi.yaml` to the samples that has the settings you need for virtual Instance and then youc an do `gradle deployPoshi` and it will use those overrides.  I think it will be more elegant possibly.

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward:force

**Pull request closed without merging**
