### PR TITLE
master-qa-15791

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-15791

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@michaelhashimoto 

Currently, the validation only allows for execute elements to have one "primaryAttribute." For macro-desktop and macro-mobile, there would be cases where we would want to have both attributes. This update allows for  both macro-desktop and macro-mobile attributes to exist in an execute element. Let me know if you have any questions. 

cc-ing @karendang

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
Will be reworked w/ some updates:
* Overload _validateHasPrimaryAttributeName and _getPrimaryAttributeName to include a list of primary attribute names that you can both 'macro-desktop' and 'macro-mobile'.
* Potentially split up the logic in _validateHasPrimaryAttributeName to first validate it is found, then check for duplicates.

**Comment by kenjiheigel** [comment]
Resent in https://github.com/michaelhashimoto/liferay-portal/pull/650

**Pull request closed without merging**
