### PR TITLE
LRAC-10191 Remove cucumber references from test.properties

### PR DESCRIPTION
**Pull request by alexcandidos**

### CODE REVIEW

**Comment by alexcandidos** [comment]
hi @michaelhashimoto , when possible, could you please review if we can remove these references? Thanks!

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by alexcandidos** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
https://github.com/michaelhashimoto/liferay-portal/pull/2106 (master)
https://github.com/brianchandotcom/liferay-portal-ee/pull/36132 (7.3.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/36133 (7.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/36134 (7.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/36135 (7.0.x)

**Pull request closed without merging**
