### PR TITLE
master-qa-18797

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-18797

### CODE REVIEW

**Comment by kenjiheigel** [comment]
This requires:
https://github.com/michaelhashimoto/liferay-portal/pull/892
https://github.com/michaelhashimoto/liferay-portal/pull/896

**Comment by kenjiheigel** [comment]
I just rebased and updated the branch, as there were some conflicts from things that went in recently.

**Comment by michaelhashimoto** [comment]
Thanks @kenjiheigel !

**Comment by kenjiheigel** [comment]
Things to update that we discussed:
"1. Rename this var TEST_BATCH_PORTAL_INSTANCE it's too specific.
2. Create a ignore.list property?
3. Don't hard-code '4', because if we want to change it we have to do a new release.
4. Maybe put the 'group division' logic into a method if possible.
5. Reassess the name of properties that we pass in. (test.batch.property.names can be reassessed, maybe get rid of 'test.batch')"

**Pull request closed without merging**
