### PR TITLE
LRCI-234

### PR DESCRIPTION
**Pull request by jpince**
https://issues.liferay.com/browse/LRCI-234

Adding jboss, tcserver, weblogic, and wildfly.

Related jenkins pull: https://github.com/michaelhashimoto/liferay-jenkins-ee/pull/817

### CODE REVIEW

**Comment by jpince** [comment]
@vicnate5 fyi. Also, I created a separate ticket for Websphere https://issues.liferay.com/browse/LRCI-269.

**Comment by michaelhashimoto** [comment]
Forwarded to BChan.
https://github.com/michaelhashimoto/liferay-portal/pull/1613 (master)
https://github.com/brianchandotcom/liferay-portal-ee/pull/31426 (7.2.x & 7.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/31427 (7.0.x)

**Comment by vicnate5** [comment]
@jpince why was tcserver added? We haven't support this app server since 7.1

**Comment by jpince** [comment]
@vicnate5 the original PR was too long ago (May 2019) for me to remember what I was thinking at the time. Feel free to ci:close the PR to BChan and work with Hashi to modify as needed.

**Pull request closed without merging**
