### PR TITLE
LRCI-3589 Add local maven repository when nexus urls are not available

### PR DESCRIPTION
**Pull request by brittneyq**
https://issues.liferay.com/browse/LRCI-3589

### CODE REVIEW

**Comment by brittneyq** [comment]
ci:test:sf

**Comment by brittneyq** [comment]
ci:test:relevant

**Comment by brittneyq** [comment]
> ###  ci:test:stable - 28 out of 28 jobs passed
> ###  ci:test:relevant - 53 out of 56 jobs passed in 1 hour 9 minutes
> Click here for more details.

Failure is unrelated to pull request.

**Comment by michaelhashimoto** [comment]
ci:forward:force

**Pull request closed without merging**
