### PR TITLE
LRCI-2671

### PR DESCRIPTION
**Pull request by petershin**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by petershin** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
Rebased here:
https://github.com/michaelhashimoto/liferay-portal/pull/2137

**Pull request closed without merging**
