### PR TITLE
master-qa-16080

### PR DESCRIPTION
**Pull request by karendang**
https://issues.liferay.com/browse/LRQA-16080

### CODE REVIEW

**Comment by karendang** [comment]
ci:retest

**Comment by karendang** [comment]
ci:retest

**Comment by karendang** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/27577

**Comment by michaelhashimoto** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/27920
https://github.com/brianchandotcom/liferay-portal/pull/27921

**Pull request closed without merging**
