### PR TITLE
master-qa-17684

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-17684

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/30286
https://github.com/brianchandotcom/liferay-portal-ee/pull/11467
https://github.com/brianchandotcom/liferay-portal-ee/pull/11468
https://github.com/brianchandotcom/liferay-portal-ee/pull/11469
https://github.com/brianchandotcom/liferay-portal-ee/pull/11470

**Pull request closed without merging**
