### PR TITLE
LRQA-FIX Add ci-merge to apio-architect

### PR DESCRIPTION
**Pull request by michaelhashimoto**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
@petershin @nhpatt - It didn't pass in the [subrepository](https://github.com/michaelhashimoto/com-liferay-apio-architect/pull/1) so I'm going to try the fix here.

**Comment by nhpatt** [comment]
The fix looks promising, I can test it in the real subrepo and fix those new sf errors.

**Comment by michaelhashimoto** [comment]
@nhpatt - Actually it doesn't look like it works either.  The test-util module still has a dependency on that module:
<pre>     [exec] 23:57:59,393 ERROR [main][ModuleFrameworkImpl:1667] Unable to start bundle com.liferay.apio.architect.test.util
     [exec] org.osgi.framework.BundleException: Could not resolve module: com.liferay.apio.architect.test.util [306]
     [exec]   Unresolved requirement: Import-Package: com.liferay.osgi.service.tracker.collections.internal
     [exec] 
     [exec] 	at org.eclipse.osgi.container.Module.start(Module.java:444)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:428)
     [exec] 	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:447)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl._startDynamicBundles(ModuleFrameworkImpl.java:1664)
     [exec] 	at com.liferay.portal.bootstrap.ModuleFrameworkImpl.startFramework(ModuleFrameworkImpl.java:411)
     [exec] 	at com.liferay.portal.module.framework.ModuleFrameworkUtilAdapter.startFramework(ModuleFrameworkUtilAdapter.java:99)
     [exec] 	at com.liferay.portal.spring.context.PortalContextLoaderListener.contextInitialized(PortalContextLoaderListener.java:291)</pre>

**Comment by nhpatt** [comment]
I've added the import in the bnd (as -conditionalpackage) with no luck either, same error

**Comment by michaelhashimoto** [comment]
ci:help

**Pull request closed without merging**
