### PR TITLE
POSHI-140 Fix validation issue and clean up code

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/POSHI-140

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test:sf

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by kenjiheigel** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:forward

cc' @pyoo47

**Pull request closed without merging**
