### PR TITLE
master-qa-16745

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-16745

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@michaelhashimoto, this should be merged after https://github.com/michaelhashimoto/liferay-portal/pull/753 goes in, as there would be conflicts in sending them separately.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/29192

**Pull request closed without merging**
