### PR TITLE
TCK3-CI 4-16

### PR DESCRIPTION
**Pull request by michaelhashimoto**

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
@dantewang @vsingleton - There were only 6 tests failures in this run:
https://test-1-11.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/217315/testReport/

**Comment by dantewang** [comment]
Thanks Michael!

Michael Hashimoto <notifications@github.com> 于 2018年4月17日周二 08:05写道：

**Comment by dantewang** [comment]
Fetched <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dantewang** [comment]
By the way @vsingleton In this run, all the 3 setSecure test cases failed.

**Comment by dantewang** [comment]
@michaelhashimoto I still can't run it myself with your branch (rebased to master), the error is "Unable to search for test file names in /opt/dev/projects/github/liferay-portal".

Here's the result: https://github.com/dantewang/liferay-portal/pull/648#issuecomment-381818382

Did I do anything wrong during rebasing?

**Pull request closed without merging**
