### PR TITLE
master-qa-16401

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-16401

### CODE REVIEW

**Comment by kenjiheigel** [comment]
@michaelhashimoto, there will be issues cherry picking this to the 6.2 and 6.1 branches. I've sent you separate pulls for those:
https://github.com/michaelhashimoto/liferay-portal-ee/pull/1686
https://github.com/michaelhashimoto/liferay-portal-ee/pull/1687

Let me know if there's issues.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@michaelhashimoto, I actually needed the poshi changes in my explicit variable update, so I sent it in my PR to BChiu. 

Will be better to wait on that one to go in first, then i'll rebase this pull.

**Comment by kenjiheigel** [comment]
I've rebased the pull, so it only contains changes to the SF logic.

**Comment by michaelhashimoto** [comment]
Pushed to BChan.
https://github.com/hhuijser/liferay-portal/pull/2397
https://github.com/hhuijser/liferay-portal-ee/pull/2511
https://github.com/hhuijser/liferay-portal-ee/pull/2512

**Pull request closed without merging**
