### PR TITLE
master-qa-20191

### PR DESCRIPTION
**Pull request by kevin-yen**
https://issues.liferay.com/browse/LRQA-20191

### CODE REVIEW

**Comment by kevin-yen** [comment]
ci:retest

**Comment by kevin-yen** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
Pushed to BChan. (Basic validation)
https://github.com/brianchandotcom/liferay-portal/pull/33812

**Comment by michaelhashimoto** [comment]
The main questions I have about this implementation is...
* I thought we were going to have end users use full class names, but we are assuming that the class we are going to use is at this package. (com.liferay.poshi.runner.util)
* I think we need to rethink the name of the new class: ExternalMethod

**Comment by michaelhashimoto** [comment]
Please see me when you come in on Monday.

**Pull request closed without merging**
