### PR TITLE
LRCI-1418 Make all cucumber result objects serializable

### PR DESCRIPTION
**Pull request by pyoo47**
http://issues.liferay.com/browse/LRCI-1418

### CODE REVIEW

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by pyoo47** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:forward

**Pull request closed without merging**
