### PR TITLE
LRQA-BLADE_FIREFOX test

### PR DESCRIPTION
**Pull request by michaelhashimoto**

### CODE REVIEW

**Comment by lawrence-lee** [comment]
I dont recognize this error ci:retest

**Comment by lawrence-lee** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
@lawrence-lee - I'm re-running it here:
https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/601/

I think master is clean again?

**Comment by lawrence-lee** [comment]
@michaelhashimoto I made more fixes to my branch.  ci:retest

**Comment by lawrence-lee** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
@lawrence-lee - I re-ran this one, it needs to have my jenkins branch otherwise it'll still point to the liferay/2.x branch.  This new build will point to your lawrence-lee/2.xfirefox branch.

https://test-5-1.liferay.com/job/test-portal-acceptance-pullrequest(master)/602/parameters/

**Comment by lawrence-lee** [comment]
@michaelhashimoto I'm not sure which test result to believe

**Pull request closed without merging**
