### PR TITLE
LPS-74610 Simple Socks Proxy | master

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LPS-74610

### CODE REVIEW

**Comment by jpince** [comment]
@michaelhashimoto BlogsUsecase#DemoTrackbackURL is failing for the same error as in [upstream](https://testray.liferay.com/home/-/testray/case_results/85491645?tab=history), I guess this will need some more work after the change is merged?

**Comment by tomwang2011** [comment]
@michaelhashimoto try adding localhost as one of the allowedhosts, thanks!

**Comment by michaelhashimoto** [comment]
I'm trying this same test out on master-private.

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by tomwang2011** [comment]
@michaelhashimoto I added one more commit for this at https://github.com/michaelhashimoto/liferay-portal/pull/1149/commits/2c5dc26697f6837a822b9fa652bb897aeb02a3ff, this will printout the blocked hostname so we can see where the test is trying to access, thanks!

**Pull request closed without merging**
