### PR TITLE
LRQA-36940 Use custom memory settings for poshi

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-36940

Fixes the tests run here: https://github.com/kenjiheigel/liferay-portal/pull/404#issuecomment-355633014. Going to still test this pull normally to make sure nothing else breaks with these changes. I'll send the backports for these, cause we might not be able to cherry pick it all.

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:test

**Comment by kenjiheigel** [comment]
Backport pulls: 
https://github.com/michaelhashimoto/liferay-portal-ee/pull/2033
https://github.com/michaelhashimoto/liferay-portal-ee/pull/2034
https://github.com/michaelhashimoto/liferay-portal-ee/pull/2035
https://github.com/michaelhashimoto/liferay-portal-ee/pull/2036
https://github.com/michaelhashimoto/liferay-portal-ee/pull/2037

Note that we can cherry pick from this branch to 7.0.x. It can't be cherry picked to 6.2 and below, but the 6.2 and 6.1 pulls can be cherry picked within themselves.

**Comment by kenjiheigel** [comment]
@michaelhashimoto, I finished testing 6.2, and it works in the PR tester as well as solving the memory issues over there. If the tests pass here, you can push all of them up to BChan.

**Comment by michaelhashimoto** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/54149 (master)
https://github.com/brianchandotcom/liferay-portal-ee/pull/19122 (7.0.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/19123 (ee-6.2.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/19124 (ee-6.2.10)
https://github.com/brianchandotcom/liferay-portal-ee/pull/19125 (ee-6.1.x)
https://github.com/brianchandotcom/liferay-portal-ee/pull/19126 (ee-6.1.30)

**Pull request closed without merging**
