### PR TITLE
LRCI-1258 Split project template tests

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1258

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by lawrence-lee** [comment]
ci:test:project-templates

**Comment by lawrence-lee** [comment]
it saves ~30 min on the integration tests. So that's a good savings. Can we go ahead with these changes? 

Thanks!

**Comment by michaelhashimoto** [comment]
@lawrence-lee - I pushed this along to BChan.  Thanks!
https://github.com/michaelhashimoto/liferay-portal/pull/1461

**Pull request closed without merging**
