### PR TITLE
LRCI-2193 Add chat password properties for poshi properties

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-2193

@brianchandotcom - If this looks okay can this be backported to `7.3.x`, `7.2.x`, `7.1.x`, & `7.0.x`?

These are just placeholders, I will put the real passwords in `liferay-jenkins-ee` if these names look okay.

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:reevaluate:1167401_8186

**Comment by brianchandotcom** [comment]
Nice @michaelhashimoto see 47aa84f3b08750630a6bb9caed8b22214f7e096a

**Comment by brianchandotcom** [comment]
Repasted link to 47aa84f3b08750630a6bb9caed8b22214f7e096a @michaelhashimoto

**Pull request closed without merging**
