### PR TITLE
master-qa-16980

### PR DESCRIPTION
**Pull request by kenjiheigel**
https://issues.liferay.com/browse/LRQA-16980

### CODE REVIEW

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
@michaelhashimoto, I'll send PortalSmoke#Smoke changes to Brian Chiu after this gets merged in, in a separate pull request.

**Comment by kenjiheigel** [comment]
ci:retest

**Comment by kenjiheigel** [comment]
Sent a separate pull for legacy branches which should have selenium builder updates:
https://github.com/michaelhashimoto/liferay-portal-ee/pull/1752

**Comment by michaelhashimoto** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/29118
https://github.com/brianchandotcom/liferay-portal-ee/pull/11042
https://github.com/brianchandotcom/liferay-portal-ee/pull/11043
https://github.com/brianchandotcom/liferay-portal-ee/pull/11044
https://github.com/brianchandotcom/liferay-portal-ee/pull/11045

**Pull request closed without merging**
