### PR TITLE
tck3-ci-2

### PR DESCRIPTION
**Pull request by michaelhashimoto**
Split into 2 different groups of tests

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by dantewang** [comment]
The following test failures disappear:

Expected:

- V2AddlPortletTests_SPEC2_15_EventEventHandling_eventProcessEvent4
- V2AddlPortletTests_SPEC2_6_RenderConfig_getContainerRuntimeOptions4
- V2AddlPortletTests_SPEC2_6_RenderConfig_getProcessingEventQnames3
- V2AddlPortletTests_SPEC2_6_RenderConfig_getPublishingEventQnames3

Unexpected:

- V2AddlResponseTests_SPEC2_12_Event_cookie7

The following unexpected failures appear:

- V2AddlResponseTests_SPEC2_12_Action_cookie1
- V2AddlResponseTests_SPEC2_12_Action_cookie2
- V2AddlResponseTests_SPEC2_12_Action_cookie3
- V2AddlResponseTests_SPEC2_12_Action_cookie4
- V2AddlResponseTests_SPEC2_12_Action_redirect1
- V2AddlResponseTests_SPEC2_12_Action_redirect12
- V2AddlResponseTests_SPEC2_12_Action_redirect14
- V2AddlResponseTests_SPEC2_12_Event_cookie5
- V2AddlResponseTests_SPEC2_12_Event_cookie6
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getAttribute
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getAttributeNames
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getAuthType
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getCharacterEncoding
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getContentLength
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getContentType
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getContextPath
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getCookies
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getDateHeader
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getHeader
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getHeaderNames
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getHeaders
- V2DispatcherReqRespTests1_SPEC2_19_ForwardJSPActionRequest_getIntHeader
- V2SigTestsEnv_CacheControl_SIGRender_hasGetETag
- V2SigTestsEnv_CacheControl_SIGRender_hasGetETagReturns
- V2SigTestsEnv_CacheControl_SIGRender_hasGetExpirationTime
- V2SigTestsEnv_CacheControl_SIGRender_hasGetExpirationTimeReturns
- V2SigTestsEnv_CacheControl_SIGRender_hasIsPublicScope
- V2SigTestsEnv_CacheControl_SIGRender_hasIsPublicScopeReturns
- V2SigTestsEnv_CacheControl_SIGRender_hasSetETag
- V2SigTestsEnv_CacheControl_SIGRender_hasSetETagReturns
- V2URLTests_BaseURL_ApiRenderActurl_toString
- V2URLTests_BaseURL_ApiRenderActurl_writeA1
- V2URLTests_BaseURL_ApiRenderActurl_writeB1
- V2URLTests_BaseURL_ApiRenderRenurl_addProperty1
- V2URLTests_BaseURL_ApiRenderRenurl_addProperty3
- V2URLTests_BaseURL_ApiRenderRenurl_getParameterMap1
- V2URLTests_BaseURL_ApiRenderRenurl_getParameterMap2
- V2URLTests_BaseURL_ApiRenderRenurl_getParameterMap6
- V2URLTests_BaseURL_ApiRenderRenurl_setParameterA1
- V2URLTests_BaseURL_ApiRenderRenurl_setParameterA2
- V2URLTests_BaseURL_ApiRenderRenurl_setParameterA3
- V2URLTests_BaseURL_ApiRenderRenurl_setParameterA6
- V2URLTests_BaseURL_ApiRenderRenurl_setParameterA7
- V2URLTests_BaseURL_ApiRenderRenurl_setParameterA8
- V2URLTests_BaseURL_ApiRenderRenurl_setParameterB1
- V2URLTests_BaseURL_ApiRenderRenurl_setParameterB2
- V2URLTests_BaseURL_ApiRenderRenurl_setParameterB3
- V2URLTests_BaseURL_ApiRenderRenurl_setParameterB6
- V2URLTests_BaseURL_ApiRenderRenurl_setParameterB8
- V2URLTests_BaseURL_ApiRenderRenurl_setParameters10
- V2URLTests_BaseURL_ApiRenderRenurl_setParameters12
- V2URLTests_BaseURL_ApiRenderRenurl_setParameters2
- V2URLTests_BaseURL_ApiRenderRenurl_setParameters7

All are selenium errors, it seems some portlets were not successfully deployed when test started?

**Comment by michaelhashimoto** [comment]
ci:test

@dantewang - I saw something weird with the reference to the tck3 branch.  I feel like the history of the branch and the rebasing was a little off.

I created a new pull request for portals-pluto based off of our tck3 branch.
https://github.com/michaelhashimoto/portals-pluto/pull/1

Hopefully this is the reason there were unexpected failures.

**Comment by michaelhashimoto** [comment]
@dantewang - It looks like the tests that you mentioned in the above comment aren't failing anymore.  do you know if it looks like the right list now?  let me know.

**Comment by dantewang** [comment]
@michaelhashimoto Thanks! Yeah, only got one unexpected failure: V2PortletTagLibraryTests2_SPEC2_26_IncludeJSPRender_actionURL1

Also Selenium failure, which can be a random one.

**Comment by dantewang** [comment]
ci:retest

**Comment by dantewang** [comment]
Hmm 147 after retest. @michaelhashimoto

**Comment by michaelhashimoto** [comment]
@dantewang - So it's inconsistently failing.

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
ci:test

**Comment by michaelhashimoto** [comment]
@dantewang - I made a list of runs that we made here:
* 124 Tests Failed. - [Attempt #1](https://test-1-16.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/191400/)
* 147 Tests Failed. - [Attempt #2](https://test-1-4.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/198798/)
* 267 Tests Failed. - [Attempt #3](https://test-1-14.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/198515/)
* 122 Tests Failed. - [Attempt #4](https://test-1-21.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/132509/)
* 122 Tests Failed. - [Attempt #5](https://test-1-22.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/52123/)
* 205 Tests Failed. - [Attempt #6](https://test-1-6.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/184464/)
* 122 Tests Failed. - [Attempt #7](https://test-1-7.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/178602/)

It is pretty inconsistent, my guess is that most of the inconsistent failures are due to WebDriver issues.  Browser testing is a little unstable, and there's lots of checks and stuff that the Portal QA Team has put into their browser tests to help make things more stable.  What do you think?

**Pull request closed without merging**
