### PR TITLE
LRCI-1258 Add support for different project templates batches

### PR DESCRIPTION
**Pull request by michaelhashimoto**
https://issues.liferay.com/browse/LRCI-1258

@lawrence-lee @jpince @vicnate5 - Here's the pull to add project template batches back into *ci:test:stable* & *ci:test:relevant*.

It should be running much faster now.

Thanks!

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by michaelhashimoto** [comment]
ci:test:sf

**Comment by michaelhashimoto** [comment]
ci:forward

**Comment by jpince** [comment]
@michaelhashimoto thank you!

**Pull request closed without merging**
