### PR TITLE
Master-lrqa-16480

### PR DESCRIPTION
**Pull request by stmerriss**
https://issues.liferay.com/browse/lrqa-16480

### CODE REVIEW

**Comment by brianchiu** [comment]
ci:retest

**Comment by stmerriss** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
ci:retest

**Comment by brianwulbern** [comment]
ci:retest

**Comment by michaelhashimoto** [comment]
Pushed to BChan.
https://github.com/brianchandotcom/liferay-portal/pull/35231
https://github.com/brianchandotcom/liferay-portal-ee/pull/12329
https://github.com/brianchandotcom/liferay-portal-ee/pull/12330
https://github.com/brianchandotcom/liferay-portal-ee/pull/12331
https://github.com/brianchandotcom/liferay-portal-ee/pull/12332

**Pull request closed without merging**
