### PR TITLE
LRCI-1305 Add spira artifact serialization to allow for more optimization

### PR DESCRIPTION
**Pull request by pyoo47**
https://issues.liferay.com/browse/LRCI-1305

Please publish after merging

### CODE REVIEW

**Comment by pyoo47** [comment]
@michaelhashimoto Please see my changes in this pull request and retest. If there are not issues, please go ahead and forward to BChan.

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by pyoo47** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
Pushed to Peter.
https://github.com/pyoo47/liferay-portal/pull/1312

**Pull request closed without merging**
